export const packetNames = {
  user: {
    C_RegisterRequest: 'C_RegisterRequest',
    S_RegisterResponse: 'S_RegisterResponse',
    C_LoginRequest: 'C_LoginRequest',
    S_LoginResponse: 'S_LoginResponse',
    C_SelectCharacterRequest: 'C_SelectCharacterRequest',
    S_Enter: 'S_Enter',
    S_Spawn: 'S_Spawn',
    S_Despawn: 'S_Despawn',
  },
  town: {
    C_Move: 'C_Move',
    S_Move: 'S_Move',
    C_Animation: 'C_Animation',
    S_Animation: 'S_Animation',
    C_PartyRequest: 'C_PartyRequest',
    S_PartyResponse: 'S_PartyResponse',
  },
  chat: {
    C_Chat: 'C_Chat',
    S_Chat: 'S_Chat',
  },
  inventory: {
    C_BuyItemRequest: 'C_BuyItemRequest',
    S_BuyItemResponse: 'S_BuyItemResponse',
    C_EquipItemRequest: 'C_EquipItemRequest',
    S_EquipItemResponse: 'S_EquipItemResponse',
    C_DisrobeItemRequest: 'C_DisrobeItemRequest',
    S_DisrobeItemResponse: 'S_DisrobeItemResponse',
    C_ActiveItemRequest: 'C_ActiveItemRequest',
    S_ActiveItemRequest: 'S_ActiveItemRequest',
  },
  dungeon: {
    C_EnterDungeon: 'C_EnterDungeon',
    S_EnterDungeon: 'S_EnterDungeon',
    S_LeaveDungeon: 'S_LeaveDungeon',
    S_ScreenText: 'S_ScreenText',
    S_ScreenDone: 'S_ScreenDone',
  },
};
